kubeconfig: |
  apiVersion: v1
  clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSU
      server: https://api.nonexistent.arcalot.io:6443
    name: arcaflow
  contexts:
  - context:
      cluster: arcaflow
      user: admin
    name: admin
  current-context: admin
  kind: Config
  preferences: {}
  users:
  - name: admin
    user:
      client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FUUNBVEUtLS0tLQo=
      client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEF
  - name: sysadmin
    user:
      token: sha256~2Z70unz91xNLI43k7MnM_mTbIfwe1EVHuxEXDiFWM9c